import 'jquery'
import 'bootstrap'

import 'bootstrap/dist/css/bootstrap'
import 'font-awesome/css/font-awesome'
import 'admin-lte/dist/css/AdminLTE'
import 'admin-lte/dist/css/skins/skin-green'
import '../src/events.scss'
import '../src/header.scss'
import '../src/qualifiers.scss'
import '../src/teams.scss'
